accounting-software:
  # accounting software implmented in the app.adapters.accounting_software module
  Xero:
    balance-sheet-url: "https://dummy-url.com/balance-sheet"
  MYOB:
    balance-sheet-url: "https://dummy-url.com/balance-sheet"
    api-key: "<Some api key here>"

rule-engine:
  # rules implemented in services.preassessment.rules module
  # order of rules may matter to some strategies
  rules:
    profit-last-year:
      active: true
    assets-gt-loan:
      active: true

  # rules implemented in services.preassessment.strategies module
  strategies:
    sequential:
      active: true
    aggressive:
      active: false
    conservative:
      active: false

decision-engine:
  decision-engine-url: "https://dummy-url.com/decision-engine"
